version: '3'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=theminingking.com
      - LETSENCRYPT_HOST=theminingking.com
      - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
    expose:
      - 80
    volumes:
      - ./public:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy
